# Generated by Django 4.0.4 on 2022-04-23 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_membre_delete_equipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='projet',
        ),
        migrations.DeleteModel(
            name='Membre',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
    ]
