# Generated by Django 4.0.4 on 2022-04-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Informations',
            new_name='Information',
        ),
    ]
