# Generated by Django 4.0.4 on 2022-04-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_informations_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='projet',
            name='couverture_Projet',
            field=models.ImageField(upload_to='ProjectImages/'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='couverture_theme',
            field=models.ImageField(upload_to=''),
        ),
    ]
