# Generated by Django 4.0.4 on 2022-04-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_image_image_alter_projet_couverture_projet_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='projet',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.RemoveField(
            model_name='video',
            name='projet',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
