# Generated by Django 4.0.4 on 2022-04-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0008_remove_image_projet_delete_information_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('adresse', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Images/PersonneImages')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('couverture', models.ImageField(upload_to='ProjectImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('nom', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('couverture', models.ImageField(upload_to='ThemeImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projet')),
            ],
        ),
        migrations.AddField(
            model_name='projet',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.theme'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projet')),
            ],
        ),
    ]
