# Generated by Django 4.0.4 on 2022-04-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='priorite',
            field=models.IntegerField(choices=[(0, 'Low'), (1, 'Normal'), (2, 'High')], default=0),
        ),
    ]
