# Generated by Django 4.0.4 on 2022-04-25 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='Images/'),
        ),
        migrations.AlterField(
            model_name='personne',
            name='image',
            field=models.ImageField(upload_to='PersonneImages/'),
        ),
    ]
