# Generated by Django 4.0.4 on 2022-05-01 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_image_image_alter_personne_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='information',
            name='facebook',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='information',
            name='instagram',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
