# Generated by Django 4.0.4 on 2022-05-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_information_linkedin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='projet',
        ),
        migrations.DeleteModel(
            name='Information',
        ),
        migrations.DeleteModel(
            name='Personne',
        ),
        migrations.RemoveField(
            model_name='projet',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='video',
            name='projet',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Projet',
        ),
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
